--- 
abstract: go from "file" names to things
author: 
  - Ricardo Signes <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: Path-Resolver
requires: 
  Archive::Tar: 0
  Data::Section: 0
  File::ShareDir: 1
  File::Spec: 0
  Moose: 0
version: 1.000
